---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    config:
      max-line-length: 120
ratings:
  paths:
  - "**.py"
  - "**.html"
exclude_paths: []
