language: python
addon:
  - mariadb
python:
  - "2.7"
  - "3.2"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install mysqlclient
  - python manage.py syncdb
#  - ./manage/prod/loaddatabase.sh

#  - pip install -r test_requirements.txt

# environment for testing
#env:

# command to run tests
script: python manage.py check
