language: python
addon:
  - mariadb
python:
  - "2.7"
  - "3.5"

env:
  - DB_NAME=akson_prod DB_USER="" DB_PASS=""

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - mysql < ./database/drop_and_create_database.sql
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py compilemessages
  - python manage.py collectstatic
#  - ./manage/prod/loaddatabase.sh

# command to run tests
script:
  - python manage.py check
  - python manage.py test --settings=akson_db.test_settings
  - coverage run manage.py test --settings=akson_db.test_settings
after_success: coveralls
